### ISSUE TITLE
Extension does not load on Postgres 11

### ISSUE THREAD

**Issue by danielsmeyer** [furstenheim/jsonb_deep_sum#1]
```
postgres=# CREATE EXTENSION jsonb_deep_sum;
ERROR:  could not load library "/usr/lib/postgresql/11/lib/jsonb_deep_sum.so": /usr/lib/postgresql/11/lib/jsonb_deep_sum.so: undefined symbol: PG_RETURN_JSONB
```
Should now be 'PG_RETURN_JSONB_P'?

**Comment by danielsmeyer** [comment]
Also 'PG_GETARG_JSONB_P' instead of 'PG_GETARG_JSONB'

**Comment by furstenheim** [comment]
Hi daniels,
Thanks for the issue. When I get some time I'll try to fix it. 

If you could write a PR I'd be grateful.

**Comment by furstenheim** [comment]
@danielsmeyer closing the issue since now it works in pg11 and pg10.

**Comment by danielsmeyer** [comment]
Nice one, homie!

**Comment by adriaandotcom** [comment]
Also tested in PostgreSQL 12, works great.
