### ISSUE TITLE
Publish extension to PGXN

### ISSUE THREAD

**Issue by MarkusSintonen** [furstenheim/jsonb_deep_sum#5]
I found your extension useful but it would be nice to get it published to PostgreSQL Extension Network. Would it be possible?

**Comment by furstenheim** [comment]
Sure thing.

**Comment by furstenheim** [comment]
I think that it is done https://pgxn.org/dist/jsonb_deep_sum/0.0.2/ could you please confirm that this is good? I've never used pgxn as a user

**Comment by MarkusSintonen** [comment]
Thanks it works!
